Hook up logging facilities
Hooks up libgphoto2's logging to Rust log crate, so that downstream users have easier time debugging various errors.

Example:

```
> RUST_LOG=gphoto2=error cargo run --example capture_preview
   Compiling gphoto2 v1.5.0 (/mnt/c/Users/me/Documents/gphoto2-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 18.29s
     Running `target/debug/examples/capture_preview`
001,001: No such file or directory
[2022-09-24T14:23:07Z ERROR gphoto2::context] Sorry, your Nikon camera does not support LiveView mode
Error: Unsupported operation
```