Fix segfault in StorageInfo Drop
`Vec::from_raw_parts` requires the input pointer to be allocated using Rust allocators (e.g. via `Box` or `Vec`), as it will attempt to free the result using Rust allocators as well.

Previously, this code passed libc-allocated pointers as-is to `Vec::from_raw_parts`. When Rust allocator != libc allocator, e.g. on Windows, or if custom allocator is used via `#[global_allocator]`, this caused heap corruption errors when `Vec` tried to deallocate itself during `Drop` phase:

```
...
        "Universal Serial Bus",
    ),
    path: Some(
        "usb:002,015",
    ),
    port_type: Some(
        Usb,
    ),
}
error: process didn't exit successfully: `target\debug\examples\camera_info.exe` (exit code: 0xc0000374, STATUS_HEAP_CORRUPTION)
```

After this change, the original pointer will be always freed using `libc::free` and the error is gone.